# Generated by Django 4.1.5 on 2023-01-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super', models.CharField(help_text='The name of the Supermarket.', max_length=50)),
                ('categoria', models.CharField(help_text='The name of the Category.', max_length=50)),
                ('producto', models.CharField(help_text='The name of the Product.', max_length=300)),
                ('precio', models.FloatField(help_text='The price of product')),
                ('picture', models.URLField(help_text='Picture of the product.', max_length=300)),
                ('peso_kg', models.CharField(help_text='peso kg', max_length=50)),
                ('precio_kg', models.CharField(help_text='peso kg', max_length=50)),
                ('peso_lt', models.CharField(help_text='peso lt', max_length=50)),
                ('precio_lt', models.CharField(help_text='peso lt', max_length=50)),
                ('peso_unidad', models.CharField(help_text='unidad', max_length=50)),
                ('precio_unidad', models.CharField(help_text='precio unidad', max_length=50)),
            ],
        ),
    ]
