# Generated by Django 4.1.7 on 2023-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_productos_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_super',
            name='fecha',
            field=models.DateField(default='2023-03-17', help_text='fecha ingreso'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='peso_kg',
            field=models.FloatField(help_text='peso kg'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='peso_lt',
            field=models.FloatField(help_text='peso lt'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='peso_unidad',
            field=models.FloatField(help_text='unidad'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='precio_kg',
            field=models.FloatField(help_text='peso kg'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='precio_lt',
            field=models.FloatField(help_text='peso lt'),
        ),
        migrations.AlterField(
            model_name='productos_super',
            name='precio_unidad',
            field=models.FloatField(help_text='precio unidad'),
        ),
    ]
