# Generated by Django 4.1.7 on 2023-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_productos_super_fecha_alter_productos_super_peso_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_super',
            name='fecha',
            field=models.DateField(default='2023-03-17', help_text='fecha ingreso'),
        ),
    ]
